server:
  port: 9007
spring:
  application:
    name: turbine
management:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
turbine:
  #参数指定需要收集监控信息的服务名
  app-config: eureka-consumer-hystrix
  #参数指定了集群名称为default
  # new String("default") 这个一定要用 String 来包一下，否则启动的时候会抛出异常
  cluster-name-expression: new String("default")
  #可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以 host 来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计
  combine-host-port: true