server:
  port: 9110
spring:
  application:
    name: api-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
zuul:
    routes:
      eureka-consumer-hystrix: /consumer/**
      eureka-producer: /producer/**
logging:
  level:
    org.springframework.cloud.gateway: debug

