server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8002/eureka/,http://peer3:8003/eureka/