server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/